const word = [
  {
    id: 1,
    wordName: "자만추",
    wordMean: "자연스러운 만남 추구",
    thumbsup: 10,
    created_at: Date.now(),
    userId: 4,
  },
  {
    id: 2,
    wordName: "자만추",
    wordMean: "자릿값 만원 추가",
    thumbsup: 15,
    created_at: Date.now(),
    userId: 3,
  },
  {
    id: 3,
    wordName: "자만추",
    wordMean: "자장면에 만두 추가",
    thumbsup: 5,
    created_at: Date.now(),
    userId: 2,
  },
  {
    id: 4,
    wordName: "자만추",
    wordMean: "자주 만나기 추하다",
    thumbsup: 20,
    created_at: Date.now(),
    userId: 3,
  },
  {
    id: 4,
    wordName: "자만추",
    wordMean: "자주 만나기 추하다",
    thumbsup: 20,
    created_at: Date.now(),
    userId: 3,
  },
  {
    id: 4,
    wordName: "자만추",
    wordMean: "자주 만나기 추하다",
    thumbsup: 20,
    created_at: Date.now(),
    userId: 3,
  },
  {
    id: 4,
    wordName: "자만추",
    wordMean: "자주 만나기 추하다",
    thumbsup: 20,
    created_at: Date.now(),
    userId: 3,
  },
  {
    id: 4,
    wordName: "자만추",
    wordMean: "자주 만나기 추하다",
    thumbsup: 20,
    created_at: Date.now(),
    userId: 3,
  },
];

const userInfo = [
  {
    id: 1,
    username: "김민재",
    email: "blackbean@gmail.com",
    password: "Minjae!123",
    phone: "01010101010",
    userPic: null,
    created_at: Date.now(),
  },
  {
    id: 2,
    username: "강영서",
    email: "younglady@gmail.com",
    password: "Young!123",
    phone: "01012121212",
    userPic: null,
    created_at: Date.now(),
  },
  {
    id: 3,
    username: "배윤수",
    email: "pearYoon@gmail.com",
    password: "Pear!123",
    phone: "01022222222",
    userPic: null,
    created_at: Date.now(),
  },
  {
    id: 4,
    username: "이나은",
    email: "nanni@gmail.com",
    password: "Nanni!123",
    phone: "01088888888",
    userPic: null,
    created_at: Date.now(),
  },
];

export default { userInfo, word };
